version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - .env
    # environment:
    #   POSTGRES_PASSWORD: password
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp' # don't mount tmp directory
    env_file:
      - .env
    # environment:
    #   - REDIS_URL=redis://redis:6379/0
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   - REDIS_URL=redis://redis:6379/0

volumes:
  redis:
  postgres_data:

